apiVersion: v1
kind: ConfigMap
metadata:
  name: sample
data: 
  url: google.com

---
apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
    - name: url
      valueFrom:
        configMapKeyRef:
          name: configmap
          key: url