apiVersion: v1
kind: ConfigMap
metadata:
  name: sample
data: 
  url: google.com

---
apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
    - name: centos
      image: centos:7
      command:
        - "sleep"
        - "1000"
      envFrom:
      - configMapKeyRef:
          name: url
          key:  url
          