apiVersion: v1
kind: Pod
metadata:
  name: {{ include "chart1.fullname" . }}
  labels:
    {{- include "chart1.labels" . | nindent 4 }}
spec:
  containers:
    - name: centos
      image: centos:7
      command:
        - "sleep"
        - "30"
      envFrom:
      - configMapRef:
          name: {{ include "chart1.fullname" . }}-cm
      - secretRef:
          name: {{  include "chart1.fullname" . }}-secret