{{- /*
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.podName }}
  labels:
    {{- include "chart1.labels" . | nindent 4 }}
spec:
  containers:
    - name: {{ .Values.containers.name }}
      image: {{ .Values.containers.image }}
      command:
       {{- range .Values.containers.command }}
        - {{ . | quote }}
        {{- end }}
      envFrom:
      - configMapRef:
          name: {{ include "chart1.fullname" . }}-cm
      - secretRef:
          name: {{  include "chart1.fullname" . }}-secret
          
*/ -}}

apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.podName }}
  labels:
    {{- include "chart1.labels" . | nindent 4 }}
spec:
  containers:
    - name: {{ .Values.containers.name }}
      image: {{ .Values.containers.image }}
      readinessProbe:
        tcpSocket:
          port: 8080
        initialDelaySeconds: 15
        periodSeconds: 20
      livenessProbe:
        tcpSocket:
          port: 8080
        initialDelaySeconds: 15
        periodSeconds: 10
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"